<script lang="ts">let { data } = $props();</script>
<svelte:head><title>Gatherframe — the demo studio</title><meta name="description" content="Explore a Gatherframe gallery and a read-only photography studio with sample collections, orders and activity." /></svelte:head>
<main class="demo-home">
  <section class="demo-hero">
    <div class="demo-intro">
      <p class="eyebrow">Gatherframe / interactive demo</p>
      <h1>The demo<br />studio.</h1>
      <p class="intro-copy">A gallery to explore.<br /> A studio to look around.</p>
      <div class="demo-actions"><a class="button-primary" href="/g/field-notes">Open the gallery <span aria-hidden="true">↗</span></a><a class="button-secondary" href="/admin">Explore the studio</a></div>
      <p class="demo-caption">No sign-up. Favorites stay in your browser.</p>
    </div>
    <a class="demo-hero-photo" href="/g/field-notes" aria-label="Open Field notes, the sample gallery"><img src={data.hero} alt="A quiet coastline in soft morning light" fetchpriority="high" /><div><span>Field notes</span><span>{data.count} photographs ↗</span></div></a>
  </section>
  <section class="demo-collections" aria-labelledby="collections-title"><div class="section-heading"><h2 id="collections-title">The collections.</h2><a href="/g/field-notes/browse">View every photograph ↗</a></div><div class="collection-grid">{#each data.collections as c}<a class="demo-collection" href={c.href}><img src={c.cover} alt={c.name} loading="lazy" /><div><h3>{c.name}</h3><span>{c.count} photographs ↗</span></div></a>{/each}</div></section>
  <section class="demo-bottom"><div><h2>Behind the gallery.</h2><p>Collections, sharing, print preparation and a view of gallery activity.</p></div><a class="button-secondary" href="/admin/events/1">Take the studio tour ↗</a></section>
  <p class="demo-provenance">Original AI-generated sample photographs. All names, orders and activity in this demo are fictional. Nothing can be purchased or submitted.</p>
</main>
<style>
  .demo-home{max-width:1500px;margin:auto;padding:clamp(1rem,4vw,4rem);color:#203e35}.demo-hero{display:grid;grid-template-columns:.85fr 1.15fr;gap:clamp(2rem,5vw,5rem);align-items:center}.demo-intro h1{font-family:Georgia,serif;font-weight:400;font-size:clamp(3.3rem,7.5vw,7.5rem);line-height:.98;letter-spacing:-.055em;margin:1.5rem 0}.intro-copy{font-size:clamp(1rem,1.5vw,1.3rem);line-height:1.65;color:#5e695e}.demo-actions{display:flex;gap:.65rem;flex-wrap:wrap;margin:2rem 0 .9rem}.demo-actions span{margin-left:1rem}.demo-caption{font-size:.78rem;color:#71786e}.demo-hero-photo{position:relative;display:block;overflow:hidden;border-radius:3px}.demo-hero-photo img{width:100%;height:clamp(370px,43vw,670px);object-fit:cover}.demo-hero-photo>div{position:absolute;inset:auto 0 0;display:flex;justify-content:space-between;align-items:end;gap:1rem;padding:3rem 1.5rem 1.5rem;background:linear-gradient(transparent,#14221dbb);color:#fff}.demo-hero-photo span:first-child{font-family:Georgia,serif;font-size:1.8rem}.demo-hero-photo span:last-child{font-size:.8rem}.demo-collections{margin-top:5rem}.section-heading{display:flex;align-items:baseline;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}.section-heading h2,.demo-bottom h2{font-family:Georgia,serif;font-size:clamp(1.6rem,3vw,2.5rem);font-weight:400;letter-spacing:-.025em}.section-heading>a{font-size:.85rem}.collection-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1.4rem}.demo-collection{min-width:0}.demo-collection img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:3px;transition:filter .2s}.demo-collection:hover img{filter:brightness(1.05)}.demo-collection>div{display:flex;justify-content:space-between;align-items:baseline;gap:.5rem;margin-top:1rem}.demo-collection h3{font-family:Georgia,serif;font-size:1.4rem;font-weight:400}.demo-collection span{font-size:.75rem;color:#71786e}.demo-bottom{display:flex;justify-content:space-between;align-items:center;gap:1.5rem;border-top:1px solid #d9ddd2;margin-top:4rem;padding-top:2.5rem}.demo-bottom p{color:#71786e;font-size:.9rem;margin-top:.7rem}.demo-provenance{font-size:.75rem;color:#71786e;margin-top:3rem;max-width:55rem;line-height:1.6}
  @media(max-width:767px){.demo-home{padding:1.25rem}.demo-hero{grid-template-columns:1fr;gap:1.75rem}.demo-intro h1{font-size:3.8rem;margin:1rem 0}.intro-copy br{display:none}.demo-actions{margin-top:1.25rem}.demo-hero-photo img{height:340px}.demo-collections{margin-top:2.5rem}.section-heading{align-items:start;flex-direction:column;gap:.7rem}.collection-grid{grid-template-columns:1fr;gap:1.75rem}.demo-collection img{aspect-ratio:3/2}.demo-bottom{align-items:start;flex-direction:column;margin-top:2.5rem}.demo-provenance{margin-top:2rem}}
</style>
