<script lang="ts">
  import { invalidateAll } from '$app/navigation';
  import { api } from '$lib/client/api';
  import { toast } from '$lib/client/toast.svelte';
  import { tagTree,tagPath,tagIsShared,tagDescendants,tagQuery,matchesTags,type PhotoTag } from '$shared/tags';
  let { eventId,tags,assignments,photoIds,selectedIds,baseUrl,collectionId='',chosen=$bindable<number[]>([]),mode=$bindable<'any'|'all'>('any'),untagged=$bindable(false) }:
    {eventId:number;tags:PhotoTag[];assignments:Record<number,number[]>;photoIds:number[];selectedIds:number[];baseUrl:string;collectionId?:string;chosen?:number[];mode?:'any'|'all';untagged?:boolean}=$props();
  let editing=$state<number|null>(null),name=$state(''),parent=$state(''),shared=$state(false),busy=$state(false),manage=$state(false),applyIds=$state<number[]>([]);
  const tree=$derived(tagTree(tags));
  const shareable=$derived(chosen.length>0&&chosen.every(id=>tagIsShared(tags,id)));
  const filterLink=$derived(baseUrl+(collectionId?`/c/${collectionId}`:'/browse')+tagQuery(tags.filter(t=>chosen.includes(t.id)).map(t=>t.publicId),mode));
  function toggle(id:number){untagged=false;chosen=chosen.includes(id)?chosen.filter(n=>n!==id):[...chosen,id];}
  function edit(t?:PhotoTag){editing=t?.id??null;name=t?.name??'';parent=String(t?.parentId??'');shared=t?.shared??false;manage=true;}
  async function post(body:unknown){return api<{tag?:PhotoTag}>(`/admin/api/events/${eventId}/tags`,{method:'POST',json:body});}
  async function save(){busy=true;try{const r=await post({action:'save',id:editing??undefined,name,parentId:parent?Number(parent):null,shared});if(!editing&&r.tag)applyIds=[...applyIds,r.tag.id];name='';parent='';editing=null;shared=false;await invalidateAll();toast('Project tag saved.','success');}catch(e){toast((e as Error).message,'error');}finally{busy=false;}}
  async function remove(){if(!editing||!confirm('Remove this tag and its photo labels? Photos and collections are kept.'))return;busy=true;try{await post({action:'delete',id:editing});chosen=chosen.filter(n=>n!==editing);applyIds=applyIds.filter(n=>n!==editing);edit();await invalidateAll();}catch(e){toast((e as Error).message,'error');}finally{busy=false;}}
  async function apply(action:'add'|'remove'){busy=true;try{await post({action,photoIds:selectedIds,tagIds:applyIds});await invalidateAll();toast(`Tags ${action==='add'?'added':'removed'}. Your photo selection is kept.`,'success');}catch(e){toast((e as Error).message,'error');}finally{busy=false;}}
  async function copy(link:string){try{await navigator.clipboard.writeText(link);toast('Link copied.','success');}catch{toast('Use the link beside the copy button.','error');}}
</script>
<section id="project-tags" class="border-t border-stone-100 p-4" aria-label="Project tags">
  <div class="flex flex-wrap items-center gap-2"><h3 class="font-semibold">Project tags</h3><button class="button-quiet ml-auto text-xs" onclick={()=>edit()}>+ Create tag</button><button class="button-quiet text-xs" onclick={()=>manage=!manage}>{manage?'Close editor':'Manage hierarchy'}</button></div>
  {#if !tags.length}<p class="mt-3 text-sm text-stone-500">No tags yet.</p>{/if}
  <div class="mt-3 flex flex-wrap gap-2"><button class="button-secondary text-xs" aria-pressed={!chosen.length&&!untagged} onclick={()=>{chosen=[];untagged=false;}}>All photos</button><button class="button-secondary text-xs" aria-pressed={untagged} onclick={()=>{chosen=[];untagged=true;}}>Untagged · {photoIds.filter(id=>!(assignments[id]?.length)).length}</button><label class="text-xs">Combine filters <select aria-label="Combine tag filters" bind:value={mode} class="rounded border p-2"><option value="any">Match any</option><option value="all">Match all</option></select></label></div>
  <div class="mt-3 max-h-64 overflow-y-auto space-y-1" role="group" aria-label="Filter by project tags">
    {#each tree as t(t.id)}<div class="flex items-center gap-2 rounded-lg px-2 py-1 hover:bg-stone-50"><label class="min-w-0 flex-1 flex items-center gap-2 text-sm"><input type="checkbox" checked={chosen.includes(t.id)} onchange={()=>toggle(t.id)} /><span class="break-words">{tagPath(tags,t.id)}</span><span class="text-xs text-stone-500">{photoIds.filter(id=>matchesTags(tags,assignments[id]??[],[t.id])).length}</span>{#if !tagIsShared(tags,t.id)}<span class="text-xs text-stone-500">Private</span>{/if}</label><button class="button-quiet text-xs" aria-label={`Edit ${tagPath(tags,t.id)}`} onclick={()=>edit(t)}>Edit</button>{#if tagIsShared(tags,t.id)}<a class="text-xs underline" href={`${baseUrl}/t/${t.publicId}`} target="_blank" rel="noreferrer">Open link</a><button class="button-quiet text-xs" aria-label={`Copy link for ${tagPath(tags,t.id)}`} onclick={()=>copy(`${baseUrl}/t/${t.publicId}`)}>Copy</button>{/if}</div>{/each}
  </div>
  {#if shareable}<div class="mt-3 flex flex-wrap gap-2 text-xs"><a class="underline break-all" href={filterLink} target="_blank" rel="noreferrer">Open this tag filter{collectionId?' within this collection':''}</a><button class="underline" onclick={()=>copy(filterLink)}>Copy filtered link</button><p class="w-full text-stone-500">Tag filter link only; private searches are excluded.</p></div>{/if}
  {#if manage}<form class="mt-4 grid gap-3 rounded-xl bg-stone-50 p-3 sm:grid-cols-2" onsubmit={e=>{e.preventDefault();void save();}}>
    <label class="text-xs">Tag name<input aria-label="Tag name" required maxlength="100" bind:value={name} class="mt-1 w-full rounded border p-2" /></label>
    <label class="text-xs">Inside <select aria-label="Parent tag" bind:value={parent} class="mt-1 w-full rounded border p-2"><option value="">Project root</option>{#each tree.filter(t=>!editing||!tagDescendants(tags,editing).has(t.id)) as t(t.id)}<option value={t.id}>{tagPath(tags,t.id)}</option>{/each}</select></label>
    <label class="text-sm flex items-center gap-2"><input type="checkbox" bind:checked={shared} />Show to parents / allow sharing</label><p class="text-xs text-stone-500">Parent tags must also allow sharing.</p>
    <div class="flex gap-3"><button disabled={busy} class="button-primary text-sm">{editing?'Save tag':'Create tag'}</button>{#if editing}<button type="button" disabled={busy} class="button-quiet text-sm" onclick={remove}>Remove tag</button>{/if}</div>
  </form>{/if}
  {#if selectedIds.length}<details open class="mt-4 border-t pt-3"><summary class="cursor-pointer text-sm font-semibold">Tag {selectedIds.length} selected photos</summary><div class="mt-2 max-h-48 overflow-y-auto grid gap-2 sm:grid-cols-2" role="group" aria-label="Tags to apply">{#each tree as t(t.id)}<label class="flex gap-2 text-sm"><input type="checkbox" value={t.id} bind:group={applyIds} /><span class="break-words">{tagPath(tags,t.id)}</span></label>{/each}</div><div class="mt-3 flex flex-wrap gap-2"><button class="button-primary text-sm" disabled={busy||!applyIds.length} onclick={()=>apply('add')}>Add tags to selected</button><button class="button-secondary text-sm" disabled={busy||!applyIds.length} onclick={()=>apply('remove')}>Remove tags from selected</button></div><p class="mt-2 text-xs text-stone-500">Applies to all {selectedIds.length} selected photos, including hidden selections. Tagging does not file photos into collections.</p></details>{/if}
</section>
